### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by chrisonline** [he667/StickyListSwipe#1]
Tried to add you example to my existing project.

So far so good, but I get on swipe or click always this **exception**:
`
09-04 14:22:52.423  18407-18407/com.colapps.reminder E/xxxx﹕ Erreur
    java.lang.ClassCastException: se.emilsjolander.stickylistheaders.CheckableWrapperView cannot be cast to com.colapps.reminder.swipeactionadapter.SwipeViewGroup
            at com.colapps.reminder.swipeactionadapter.SwipeActionTouchListener.onTouch(SwipeActionTouchListener.java:272)
            at android.view.View.dispatchTouchEvent(View.java:8465)
`

**Code:**
```java
    for (int i = 0; i < childCount; i++) {
       child = mListView.getChildAt(i);
                    child.getHitRect(rect);
                    if (rect.contains(x, y)) {
                        try {
--> Exception        mDownViewGroup = (SwipeViewGroup) child;
                            mDownView = mFixedBackgrounds ? mDownViewGroup.getContentView() : child;
                            if(!mFixedBackgrounds) mDownViewGroup.translateBackgrounds();
                        }
                        catch(Exception e) {
                            Log.e("xxxx", "Erreur", e);
                            mDownView = child;
                        }
                        break;
                    }
                }
```

Any help? What did I wrong?

**Comment by chrisonline** [comment]
Fixed... :-)
